apiVersion: v2
name: graylog
home: https://www.graylog.org
version: 1.7.5
appVersion: 4.0.2
description: Graylog is the centralized log management solution built to open standards for capturing, storing, and enabling real-time analysis of terabytes of machine data.
keywords:
  - graylog
  - logs
  - syslog
  - gelf
icon: https://global-uploads.webflow.com/5a218ef7897bf400019e2f16/5a218ef7897bf400019e2f60_logo-graylog.png
sources:
  - https://github.com/KongZ/charts
maintainers:
  - name: KongZ
    email: goonohc@gmail.com
dependencies:
  - name: elasticsearch
    version: 1.32.2
    repository: https://charts.helm.sh/stable
    tags:
      - install-elasticsearch
  - name: mongodb
    version: 9.3.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - install-mongodb
